apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-prod

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: myapp
      spec:
        replicas: 5
    target:
      kind: Deployment
      name: myapp

images:
  - name: nginx
    newTag: "1.25"

labels:
  - pairs:
      environment: prod
    includeSelectors: false

commonAnnotations:
  managed-by: argocd
  environment: prod
